---
# tasks file for control
    - name: Install Curl
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - python-httplib2
      tags: [ 'packages' ]
