---
# tasks file for mysql

    - name: Install tools
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - python-mysqldb

    - name: Install mysql-server
      apt:
        name: mysql-server
        state: present
      
    - name: Verify that MySQL server is up and running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: ensure mysql listening on all ports
      lineinfile:
        path: /etc/mysql/my.cnf
        regexp: ^bind-address
        line: "bind-address = {{ ansible_eth1.ipv4.address }}"
      notify: restart mysql

    - name: Verify that MySQL server is up and running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create "{{ db_name }}" database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: create demo user
      mysql_user:
        name: "{{ db_user_name }}"
        password: "{{ db_user_pass }}"
        priv: "{{ db_name }}.*:ALL"
        host: "{{ db_user_host }}"
        state: present
